using Microsoft.VisualStudio.Shell;
using System;

namespace Salesforce.VisualStudio.Services.ConnectedService.Views
{
    internal static class ThemedDialogColors
    {
        #region Autogenerated resource keys
        // These resource keys are generated by VsThemeEditor, and should be replaced when new colors are added to this category.
        public static readonly Guid Category = new Guid("5e04b2a9-e443-48db-8791-63a2a71cfbd7");

        private static ThemeResourceKey _GridHeadingBackgroundColorKey;
        private static ThemeResourceKey _GridHeadingBackgroundBrushKey;
        public static ThemeResourceKey GridHeadingBackgroundColorKey { get { return _GridHeadingBackgroundColorKey ?? (_GridHeadingBackgroundColorKey = new ThemeResourceKey(Category, "GridHeadingBackground", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey GridHeadingBackgroundBrushKey { get { return _GridHeadingBackgroundBrushKey ?? (_GridHeadingBackgroundBrushKey = new ThemeResourceKey(Category, "GridHeadingBackground", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _GridHeadingTextColorKey;
        private static ThemeResourceKey _GridHeadingTextBrushKey;
        public static ThemeResourceKey GridHeadingTextColorKey { get { return _GridHeadingTextColorKey ?? (_GridHeadingTextColorKey = new ThemeResourceKey(Category, "GridHeadingText", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey GridHeadingTextBrushKey { get { return _GridHeadingTextBrushKey ?? (_GridHeadingTextBrushKey = new ThemeResourceKey(Category, "GridHeadingText", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _GridLineColorKey;
        private static ThemeResourceKey _GridLineBrushKey;
        public static ThemeResourceKey GridLineColorKey { get { return _GridLineColorKey ?? (_GridLineColorKey = new ThemeResourceKey(Category, "GridLine", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey GridLineBrushKey { get { return _GridLineBrushKey ?? (_GridLineBrushKey = new ThemeResourceKey(Category, "GridLine", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _HeaderTextColorKey;
        private static ThemeResourceKey _HeaderTextBrushKey;
        public static ThemeResourceKey HeaderTextColorKey { get { return _HeaderTextColorKey ?? (_HeaderTextColorKey = new ThemeResourceKey(Category, "HeaderText", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey HeaderTextBrushKey { get { return _HeaderTextBrushKey ?? (_HeaderTextBrushKey = new ThemeResourceKey(Category, "HeaderText", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _HyperlinkColorKey;
        private static ThemeResourceKey _HyperlinkBrushKey;
        public static ThemeResourceKey HyperlinkColorKey { get { return _HyperlinkColorKey ?? (_HyperlinkColorKey = new ThemeResourceKey(Category, "Hyperlink", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey HyperlinkBrushKey { get { return _HyperlinkBrushKey ?? (_HyperlinkBrushKey = new ThemeResourceKey(Category, "Hyperlink", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _HyperlinkHoverColorKey;
        private static ThemeResourceKey _HyperlinkHoverBrushKey;
        public static ThemeResourceKey HyperlinkHoverColorKey { get { return _HyperlinkHoverColorKey ?? (_HyperlinkHoverColorKey = new ThemeResourceKey(Category, "HyperlinkHover", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey HyperlinkHoverBrushKey { get { return _HyperlinkHoverBrushKey ?? (_HyperlinkHoverBrushKey = new ThemeResourceKey(Category, "HyperlinkHover", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _HyperlinkPressedColorKey;
        private static ThemeResourceKey _HyperlinkPressedBrushKey;
        public static ThemeResourceKey HyperlinkPressedColorKey { get { return _HyperlinkPressedColorKey ?? (_HyperlinkPressedColorKey = new ThemeResourceKey(Category, "HyperlinkPressed", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey HyperlinkPressedBrushKey { get { return _HyperlinkPressedBrushKey ?? (_HyperlinkPressedBrushKey = new ThemeResourceKey(Category, "HyperlinkPressed", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _ListItemDisabledTextColorKey;
        private static ThemeResourceKey _ListItemDisabledTextBrushKey;
        public static ThemeResourceKey ListItemDisabledTextColorKey { get { return _ListItemDisabledTextColorKey ?? (_ListItemDisabledTextColorKey = new ThemeResourceKey(Category, "ListItemDisabledText", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey ListItemDisabledTextBrushKey { get { return _ListItemDisabledTextBrushKey ?? (_ListItemDisabledTextBrushKey = new ThemeResourceKey(Category, "ListItemDisabledText", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _SectionDividerColorKey;
        private static ThemeResourceKey _SectionDividerBrushKey;
        public static ThemeResourceKey SectionDividerColorKey { get { return _SectionDividerColorKey ?? (_SectionDividerColorKey = new ThemeResourceKey(Category, "SectionDivider", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SectionDividerBrushKey { get { return _SectionDividerBrushKey ?? (_SectionDividerBrushKey = new ThemeResourceKey(Category, "SectionDivider", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _SelectedItemActiveColorKey;
        private static ThemeResourceKey _SelectedItemActiveBrushKey;
        private static ThemeResourceKey _SelectedItemActiveTextColorKey;
        private static ThemeResourceKey _SelectedItemActiveTextBrushKey;
        public static ThemeResourceKey SelectedItemActiveColorKey { get { return _SelectedItemActiveColorKey ?? (_SelectedItemActiveColorKey = new ThemeResourceKey(Category, "SelectedItemActive", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SelectedItemActiveBrushKey { get { return _SelectedItemActiveBrushKey ?? (_SelectedItemActiveBrushKey = new ThemeResourceKey(Category, "SelectedItemActive", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SelectedItemActiveTextColorKey { get { return _SelectedItemActiveTextColorKey ?? (_SelectedItemActiveTextColorKey = new ThemeResourceKey(Category, "SelectedItemActive", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SelectedItemActiveTextBrushKey { get { return _SelectedItemActiveTextBrushKey ?? (_SelectedItemActiveTextBrushKey = new ThemeResourceKey(Category, "SelectedItemActive", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _SelectedItemInactiveColorKey;
        private static ThemeResourceKey _SelectedItemInactiveBrushKey;
        private static ThemeResourceKey _SelectedItemInactiveTextColorKey;
        private static ThemeResourceKey _SelectedItemInactiveTextBrushKey;
        public static ThemeResourceKey SelectedItemInactiveColorKey { get { return _SelectedItemInactiveColorKey ?? (_SelectedItemInactiveColorKey = new ThemeResourceKey(Category, "SelectedItemInactive", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SelectedItemInactiveBrushKey { get { return _SelectedItemInactiveBrushKey ?? (_SelectedItemInactiveBrushKey = new ThemeResourceKey(Category, "SelectedItemInactive", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SelectedItemInactiveTextColorKey { get { return _SelectedItemInactiveTextColorKey ?? (_SelectedItemInactiveTextColorKey = new ThemeResourceKey(Category, "SelectedItemInactive", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SelectedItemInactiveTextBrushKey { get { return _SelectedItemInactiveTextBrushKey ?? (_SelectedItemInactiveTextBrushKey = new ThemeResourceKey(Category, "SelectedItemInactive", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _WindowBorderColorKey;
        private static ThemeResourceKey _WindowBorderBrushKey;
        public static ThemeResourceKey WindowBorderColorKey { get { return _WindowBorderColorKey ?? (_WindowBorderColorKey = new ThemeResourceKey(Category, "WindowBorder", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowBorderBrushKey { get { return _WindowBorderBrushKey ?? (_WindowBorderBrushKey = new ThemeResourceKey(Category, "WindowBorder", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonColorKey;
        private static ThemeResourceKey _WindowButtonBrushKey;
        public static ThemeResourceKey WindowButtonColorKey { get { return _WindowButtonColorKey ?? (_WindowButtonColorKey = new ThemeResourceKey(Category, "WindowButton", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonBrushKey { get { return _WindowButtonBrushKey ?? (_WindowButtonBrushKey = new ThemeResourceKey(Category, "WindowButton", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonBorderColorKey;
        private static ThemeResourceKey _WindowButtonBorderBrushKey;
        public static ThemeResourceKey WindowButtonBorderColorKey { get { return _WindowButtonBorderColorKey ?? (_WindowButtonBorderColorKey = new ThemeResourceKey(Category, "WindowButtonBorder", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonBorderBrushKey { get { return _WindowButtonBorderBrushKey ?? (_WindowButtonBorderBrushKey = new ThemeResourceKey(Category, "WindowButtonBorder", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonDownColorKey;
        private static ThemeResourceKey _WindowButtonDownBrushKey;
        public static ThemeResourceKey WindowButtonDownColorKey { get { return _WindowButtonDownColorKey ?? (_WindowButtonDownColorKey = new ThemeResourceKey(Category, "WindowButtonDown", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonDownBrushKey { get { return _WindowButtonDownBrushKey ?? (_WindowButtonDownBrushKey = new ThemeResourceKey(Category, "WindowButtonDown", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonDownBorderColorKey;
        private static ThemeResourceKey _WindowButtonDownBorderBrushKey;
        public static ThemeResourceKey WindowButtonDownBorderColorKey { get { return _WindowButtonDownBorderColorKey ?? (_WindowButtonDownBorderColorKey = new ThemeResourceKey(Category, "WindowButtonDownBorder", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonDownBorderBrushKey { get { return _WindowButtonDownBorderBrushKey ?? (_WindowButtonDownBorderBrushKey = new ThemeResourceKey(Category, "WindowButtonDownBorder", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonDownGlyphColorKey;
        private static ThemeResourceKey _WindowButtonDownGlyphBrushKey;
        public static ThemeResourceKey WindowButtonDownGlyphColorKey { get { return _WindowButtonDownGlyphColorKey ?? (_WindowButtonDownGlyphColorKey = new ThemeResourceKey(Category, "WindowButtonDownGlyph", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonDownGlyphBrushKey { get { return _WindowButtonDownGlyphBrushKey ?? (_WindowButtonDownGlyphBrushKey = new ThemeResourceKey(Category, "WindowButtonDownGlyph", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonGlyphColorKey;
        private static ThemeResourceKey _WindowButtonGlyphBrushKey;
        public static ThemeResourceKey WindowButtonGlyphColorKey { get { return _WindowButtonGlyphColorKey ?? (_WindowButtonGlyphColorKey = new ThemeResourceKey(Category, "WindowButtonGlyph", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonGlyphBrushKey { get { return _WindowButtonGlyphBrushKey ?? (_WindowButtonGlyphBrushKey = new ThemeResourceKey(Category, "WindowButtonGlyph", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonHoverColorKey;
        private static ThemeResourceKey _WindowButtonHoverBrushKey;
        public static ThemeResourceKey WindowButtonHoverColorKey { get { return _WindowButtonHoverColorKey ?? (_WindowButtonHoverColorKey = new ThemeResourceKey(Category, "WindowButtonHover", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonHoverBrushKey { get { return _WindowButtonHoverBrushKey ?? (_WindowButtonHoverBrushKey = new ThemeResourceKey(Category, "WindowButtonHover", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonHoverBorderColorKey;
        private static ThemeResourceKey _WindowButtonHoverBorderBrushKey;
        public static ThemeResourceKey WindowButtonHoverBorderColorKey { get { return _WindowButtonHoverBorderColorKey ?? (_WindowButtonHoverBorderColorKey = new ThemeResourceKey(Category, "WindowButtonHoverBorder", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonHoverBorderBrushKey { get { return _WindowButtonHoverBorderBrushKey ?? (_WindowButtonHoverBorderBrushKey = new ThemeResourceKey(Category, "WindowButtonHoverBorder", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowButtonHoverGlyphColorKey;
        private static ThemeResourceKey _WindowButtonHoverGlyphBrushKey;
        public static ThemeResourceKey WindowButtonHoverGlyphColorKey { get { return _WindowButtonHoverGlyphColorKey ?? (_WindowButtonHoverGlyphColorKey = new ThemeResourceKey(Category, "WindowButtonHoverGlyph", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowButtonHoverGlyphBrushKey { get { return _WindowButtonHoverGlyphBrushKey ?? (_WindowButtonHoverGlyphBrushKey = new ThemeResourceKey(Category, "WindowButtonHoverGlyph", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _WindowPanelColorKey;
        private static ThemeResourceKey _WindowPanelBrushKey;
        private static ThemeResourceKey _WindowPanelTextColorKey;
        private static ThemeResourceKey _WindowPanelTextBrushKey;
        public static ThemeResourceKey WindowPanelColorKey { get { return _WindowPanelColorKey ?? (_WindowPanelColorKey = new ThemeResourceKey(Category, "WindowPanel", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WindowPanelBrushKey { get { return _WindowPanelBrushKey ?? (_WindowPanelBrushKey = new ThemeResourceKey(Category, "WindowPanel", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey WindowPanelTextColorKey { get { return _WindowPanelTextColorKey ?? (_WindowPanelTextColorKey = new ThemeResourceKey(Category, "WindowPanel", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey WindowPanelTextBrushKey { get { return _WindowPanelTextBrushKey ?? (_WindowPanelTextBrushKey = new ThemeResourceKey(Category, "WindowPanel", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _WizardFooterColorKey;
        private static ThemeResourceKey _WizardFooterBrushKey;
        public static ThemeResourceKey WizardFooterColorKey { get { return _WizardFooterColorKey ?? (_WizardFooterColorKey = new ThemeResourceKey(Category, "WizardFooter", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey WizardFooterBrushKey { get { return _WizardFooterBrushKey ?? (_WizardFooterBrushKey = new ThemeResourceKey(Category, "WizardFooter", ThemeResourceKeyType.BackgroundBrush)); } }
        #endregion
    }
}
