//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesforce.VisualStudio.Services.ConnectedService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salesforce.VisualStudio.Services.ConnectedService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Salesforce.
        ///
        ///Request:  {0}
        ///
        ///Response:  {1}.
        /// </summary>
        internal static string AuthenticationHelper_UnableToConnectToSalesforce {
            get {
                return ResourceManager.GetString("AuthenticationHelper_UnableToConnectToSalesforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the connected app.
        ///Details:  {0}.
        /// </summary>
        internal static string ConnectedAppHelper_FailedToCreateConnectedApp {
            get {
                return ResourceManager.GetString("ConnectedAppHelper_FailedToCreateConnectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce Connected App.
        /// </summary>
        internal static string ConnectedServiceInstance_Name {
            get {
                return ResourceManager.GetString("ConnectedServiceInstance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce.
        /// </summary>
        internal static string ConnectedServiceProvider_Category {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce.
        /// </summary>
        internal static string ConnectedServiceProvider_CreatedBy {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides simplified access to your organization’s data using Salesforce REST APIs..
        /// </summary>
        internal static string ConnectedServiceProvider_Description {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce Data Services.
        /// </summary>
        internal static string ConnectedServiceProvider_Name {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New user account&gt;.
        /// </summary>
        internal static string DesignTimeAuthentication_NewIdentityName {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_NewIdentityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string DesignTimeAuthentication_Summary_Custom {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_Summary_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Production).
        /// </summary>
        internal static string DesignTimeAuthentication_Summary_Production {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_Summary_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Sandbox).
        /// </summary>
        internal static string DesignTimeAuthentication_Summary_Sandbox {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_Summary_Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_AuthenticatingProgress {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_AuthenticatingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Salesforce environment to authenticate against.
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Description {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Environment_Custom {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Environment_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Environment_Production {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Environment_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox.
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Environment_Sandbox {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Environment_Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Legend {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce Data Services.
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Title {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with Salesforce..
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_UnableToAuthenticateUser {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_UnableToAuthenticateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added a Salesforce connected service to the project..
        /// </summary>
        internal static string LogMessage_AddedConnectedService {
            get {
                return ResourceManager.GetString("LogMessage_AddedConnectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding reference to {0}..
        /// </summary>
        internal static string LogMessage_AddingAssemblyReference {
            get {
                return ResourceManager.GetString("LogMessage_AddingAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding assembly references to the project..
        /// </summary>
        internal static string LogMessage_AddingAssemblyReferences {
            get {
                return ResourceManager.GetString("LogMessage_AddingAssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a Salesforce connected service to the project..
        /// </summary>
        internal static string LogMessage_AddingConnectedService {
            get {
                return ResourceManager.GetString("LogMessage_AddingConnectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding scaffold code files to the project..
        /// </summary>
        internal static string LogMessage_AddingGeneratedCode {
            get {
                return ResourceManager.GetString("LogMessage_AddingGeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding scaffold model files for Salesforce objects ({0})..
        /// </summary>
        internal static string LogMessage_AddingGeneratedCodeForObjects {
            get {
                return ResourceManager.GetString("LogMessage_AddingGeneratedCodeForObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing NuGet package &apos;{0}&apos; version {1}..
        /// </summary>
        internal static string LogMessage_AddingNuGetPackage {
            get {
                return ResourceManager.GetString("LogMessage_AddingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the object model for the Salesforce objects..
        /// </summary>
        internal static string LogMessage_BuildingObjectModel {
            get {
                return ResourceManager.GetString("LogMessage_BuildingObjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the connected app within Salesforce..
        /// </summary>
        internal static string LogMessage_CreatingConnectedApp {
            get {
                return ResourceManager.GetString("LogMessage_CreatingConnectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connected app named &apos;{0}&apos; already exists.  Retrying using &apos;{1}&apos;..
        /// </summary>
        internal static string LogMessage_DuplicateConnectedAppName {
            get {
                return ResourceManager.GetString("LogMessage_DuplicateConnectedAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the connected app that was just created; the ConsumerKey AppSetting in the config file will need to be specified..
        /// </summary>
        internal static string LogMessage_FailedReadingConnectedApp {
            get {
                return ResourceManager.GetString("LogMessage_FailedReadingConnectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ModelsHintPath &apos;{0}&apos; specified in ConnectedService.json is invalid..
        /// </summary>
        internal static string LogMessage_InvalidModelsHintPath {
            get {
                return ResourceManager.GetString("LogMessage_InvalidModelsHintPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code being added depends on NugGet package ‘{0}’ version {1}.  A newer version ({2}) is already installed.  This may cause compatibility issues..
        /// </summary>
        internal static string LogMessage_NewerMajorVersionNuGetPackageExists {
            get {
                return ResourceManager.GetString("LogMessage_NewerMajorVersionNuGetPackageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading NuGet package &apos;{0}&apos; from version {1} to {2}.  A major version upgrade may introduce compatibility issues with existing code..
        /// </summary>
        internal static string LogMessage_OlderMajorVersionNuGetPackageExists {
            get {
                return ResourceManager.GetString("LogMessage_OlderMajorVersionNuGetPackageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CLR type found for the Salesforce soap type &apos;{0}&apos; used on the &apos;{1}.{2}&apos; property..
        /// </summary>
        internal static string LogMessage_UnsupportedSoapType {
            get {
                return ResourceManager.GetString("LogMessage_UnsupportedSoapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated the Salesforce connected service within the project..
        /// </summary>
        internal static string LogMessage_UpdatedConnectedService {
            get {
                return ResourceManager.GetString("LogMessage_UpdatedConnectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding settings to the project&apos;s config file..
        /// </summary>
        internal static string LogMessage_UpdatingConfigFile {
            get {
                return ResourceManager.GetString("LogMessage_UpdatingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the Salesforce connected service within the project..
        /// </summary>
        internal static string LogMessage_UpdatingConnectedService {
            get {
                return ResourceManager.GetString("LogMessage_UpdatingConnectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading NuGet package &apos;{0}&apos; from version {1} to {2}..
        /// </summary>
        internal static string LogMessage_UpgradingNuGetPackage {
            get {
                return ResourceManager.GetString("LogMessage_UpgradingNuGetPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL (example: https://yoursite-dev-ed.my.salesforce.com).
        /// </summary>
        internal static string MyDomainViewModel_ErrorMessage {
            get {
                return ResourceManager.GetString("MyDomainViewModel_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Objects.
        /// </summary>
        internal static string ObjectSelectionViewModel_AllObjects {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_AllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select objects to scaffold models within your application.
        /// </summary>
        internal static string ObjectSelectionViewModel_Description {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Selection.
        /// </summary>
        internal static string ObjectSelectionViewModel_Legend {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the Salesforce objects.
        ///{0}.
        /// </summary>
        internal static string ObjectSelectionViewModel_LoadingError {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Objects....
        /// </summary>
        internal static string ObjectSelectionViewModel_LoadingObjectsProgress {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_LoadingObjectsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce Data Services.
        /// </summary>
        internal static string ObjectSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Salesforce connected app is named: {0} .
        /// </summary>
        internal static string RuntimeAuthentication_ConsumerKeyComment {
            get {
                return ResourceManager.GetString("RuntimeAuthentication_ConsumerKeyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose runtime authentication settings.
        /// </summary>
        internal static string RuntimeAuthenticationConfigViewModel_Description {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationConfigViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Authentication Config.
        /// </summary>
        internal static string RuntimeAuthenticationConfigViewModel_Legend {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationConfigViewModel_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce Data Services.
        /// </summary>
        internal static string RuntimeAuthenticationConfigViewModel_Title {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationConfigViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a runtime authentication model.
        /// </summary>
        internal static string RuntimeAuthenticationTypeViewModel_Description {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationTypeViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Authentication.
        /// </summary>
        internal static string RuntimeAuthenticationTypeViewModel_Legend {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationTypeViewModel_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce Data Services.
        /// </summary>
        internal static string RuntimeAuthenticationTypeViewModel_Title {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationTypeViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading the {0} user settings.
        ///{1}.
        /// </summary>
        internal static string UserSettingsHelper_FailedLoading {
            get {
                return ResourceManager.GetString("UserSettingsHelper_FailedLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed saving the {0} user settings.
        ///{1}.
        /// </summary>
        internal static string UserSettingsHelper_FailedSaving {
            get {
                return ResourceManager.GetString("UserSettingsHelper_FailedSaving", resourceCulture);
            }
        }
    }
}
