//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesforce.VisualStudio.Services.ConnectedService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salesforce.VisualStudio.Services.ConnectedService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Salesforce.
        ///
        ///Request:  {0}
        ///
        ///Response:  {1}.
        /// </summary>
        internal static string AuthenticationHelper_UnableToConnectToSalesforce {
            get {
                return ResourceManager.GetString("AuthenticationHelper_UnableToConnectToSalesforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the connected app.
        ///Details:  {0}.
        /// </summary>
        internal static string ConnectedAppHelper_FailedToCreateConnectedApp {
            get {
                return ResourceManager.GetString("ConnectedAppHelper_FailedToCreateConnectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce Connected App.
        /// </summary>
        internal static string ConnectedServiceInstance_Name {
            get {
                return ResourceManager.GetString("ConnectedServiceInstance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce.
        /// </summary>
        internal static string ConnectedServiceProvider_Category {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce.
        /// </summary>
        internal static string ConnectedServiceProvider_CreatedBy {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides programmatic access to your organization’s information using simple, powerful, and secure application programming interfaces (APIs). APIs open up a platform to developers and enable them to explore different ways to integrate platform capabilities within their own applications..
        /// </summary>
        internal static string ConnectedServiceProvider_Description {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce for .NET.
        /// </summary>
        internal static string ConnectedServiceProvider_Name {
            get {
                return ResourceManager.GetString("ConnectedServiceProvider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New user account&gt;.
        /// </summary>
        internal static string DesignTimeAuthentication_NewIdentityName {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_NewIdentityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string DesignTimeAuthentication_Summary_Custom {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_Summary_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Production).
        /// </summary>
        internal static string DesignTimeAuthentication_Summary_Production {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_Summary_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Sandbox).
        /// </summary>
        internal static string DesignTimeAuthentication_Summary_Sandbox {
            get {
                return ResourceManager.GetString("DesignTimeAuthentication_Summary_Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Environment_Custom {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Environment_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Environment_Production {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Environment_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox.
        /// </summary>
        internal static string DesignTimeAuthenticationViewModel_Environment_Sandbox {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationViewModel_Environment_Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Salesforce environment to authenticate against.
        /// </summary>
        internal static string DesignTimeAuthenticationWizardPage_Description {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string DesignTimeAuthenticationWizardPage_Legend {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationWizardPage_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce for .NET.
        /// </summary>
        internal static string DesignTimeAuthenticationWizardPage_Title {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate with Salesforce..
        /// </summary>
        internal static string DesignTimeAuthenticationWizardPage_UnableToAuthenticateUser {
            get {
                return ResourceManager.GetString("DesignTimeAuthenticationWizardPage_UnableToAuthenticateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added reference to {0}..
        /// </summary>
        internal static string LogMessage_AddedAssemblyReference {
            get {
                return ResourceManager.GetString("LogMessage_AddedAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added assembly references to the project..
        /// </summary>
        internal static string LogMessage_AddedAssemblyReferences {
            get {
                return ResourceManager.GetString("LogMessage_AddedAssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added a Salesforce connected service to the project..
        /// </summary>
        internal static string LogMessage_AddedConnectedService {
            get {
                return ResourceManager.GetString("LogMessage_AddedConnectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added scaffold code files to the project..
        /// </summary>
        internal static string LogMessage_AddedGeneratedCode {
            get {
                return ResourceManager.GetString("LogMessage_AddedGeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added NuGet packages to the project..
        /// </summary>
        internal static string LogMessage_AddedNuGetPackages {
            get {
                return ResourceManager.GetString("LogMessage_AddedNuGetPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding assembly references to the project..
        /// </summary>
        internal static string LogMessage_AddingAssemblyReferences {
            get {
                return ResourceManager.GetString("LogMessage_AddingAssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a Salesforce connected service to the project..
        /// </summary>
        internal static string LogMessage_AddingConnectedService {
            get {
                return ResourceManager.GetString("LogMessage_AddingConnectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding scaffold code files to the project..
        /// </summary>
        internal static string LogMessage_AddingGeneratedCode {
            get {
                return ResourceManager.GetString("LogMessage_AddingGeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding NuGet packages to the project..
        /// </summary>
        internal static string LogMessage_AddingNuGetPackages {
            get {
                return ResourceManager.GetString("LogMessage_AddingNuGetPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building the object model for the Salesforce objects..
        /// </summary>
        internal static string LogMessage_BuildingObjectModel {
            get {
                return ResourceManager.GetString("LogMessage_BuildingObjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished building the object model for {0} Salesforce objects..
        /// </summary>
        internal static string LogMessage_BuiltObjectModel {
            get {
                return ResourceManager.GetString("LogMessage_BuiltObjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created the connected app within Salesforce..
        /// </summary>
        internal static string LogMessage_CreatedConnectedApp {
            get {
                return ResourceManager.GetString("LogMessage_CreatedConnectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the connected app within Salesforce..
        /// </summary>
        internal static string LogMessage_CreatingConnectedApp {
            get {
                return ResourceManager.GetString("LogMessage_CreatingConnectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to the assembly {0} already exists in the project..
        /// </summary>
        internal static string LogMessage_DetectedExistingAssemblyReference {
            get {
                return ResourceManager.GetString("LogMessage_DetectedExistingAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting telemetry OptIn status..
        /// </summary>
        internal static string LogMessage_DetectingTelemetryOptInStatus {
            get {
                return ResourceManager.GetString("LogMessage_DetectingTelemetryOptInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry OptIn status is &apos;{0}&apos;..
        /// </summary>
        internal static string LogMessage_DetectingTelemetryOptInStatusCompleted {
            get {
                return ResourceManager.GetString("LogMessage_DetectingTelemetryOptInStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add reference to {0} - {1}.
        /// </summary>
        internal static string LogMessage_FailedAddingAssemblyReference {
            get {
                return ResourceManager.GetString("LogMessage_FailedAddingAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add Salesforce connected service to the project - {0}.
        /// </summary>
        internal static string LogMessage_FailedAddingConnectedService {
            get {
                return ResourceManager.GetString("LogMessage_FailedAddingConnectedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the connected app that was just created; the ConsumerKey AppSetting in the config file will need to be specified.&quot;.
        /// </summary>
        internal static string LogMessage_FailedReadingConnectedApp {
            get {
                return ResourceManager.GetString("LogMessage_FailedReadingConnectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log telemetry data.
        ///{0}.
        /// </summary>
        internal static string LogMessage_FailedToLogTelemetryData {
            get {
                return ResourceManager.GetString("LogMessage_FailedToLogTelemetryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to gather and log telemetry data..
        /// </summary>
        internal static string LogMessage_LoggingTelemetryData {
            get {
                return ResourceManager.GetString("LogMessage_LoggingTelemetryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished gathering and logging telemetry data..
        /// </summary>
        internal static string LogMessage_LoggingTelemetryDataCompleted {
            get {
                return ResourceManager.GetString("LogMessage_LoggingTelemetryDataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigated to the getting started web page..
        /// </summary>
        internal static string LogMessage_PresentedGettingStarted {
            get {
                return ResourceManager.GetString("LogMessage_PresentedGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to the getting started web page..
        /// </summary>
        internal static string LogMessage_PresentingGettingStarted {
            get {
                return ResourceManager.GetString("LogMessage_PresentingGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CLR type found for the Salesforce soap type &apos;{0}&apos; used on the &apos;{1}.{2}&apos; property..
        /// </summary>
        internal static string LogMessage_UnsupportedSoapType {
            get {
                return ResourceManager.GetString("LogMessage_UnsupportedSoapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added settings to the project&apos;s config file..
        /// </summary>
        internal static string LogMessage_UpdatedConfigFile {
            get {
                return ResourceManager.GetString("LogMessage_UpdatedConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding settings to the project&apos;s config file..
        /// </summary>
        internal static string LogMessage_UpdatingConfigFile {
            get {
                return ResourceManager.GetString("LogMessage_UpdatingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL (example: https://yoursite-dev-ed.my.salesforce.com).
        /// </summary>
        internal static string MyDomainViewModel_ErrorMessage {
            get {
                return ResourceManager.GetString("MyDomainViewModel_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Objects.
        /// </summary>
        internal static string ObjectSelectionViewModel_AllObjects {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_AllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while retrieving the Salesforce objects.
        ///{0}.
        /// </summary>
        internal static string ObjectSelectionViewModel_LoadingError {
            get {
                return ResourceManager.GetString("ObjectSelectionViewModel_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select objects to scaffold models within your application.
        /// </summary>
        internal static string ObjectSelectionWizardPage_Description {
            get {
                return ResourceManager.GetString("ObjectSelectionWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Selection.
        /// </summary>
        internal static string ObjectSelectionWizardPage_Legend {
            get {
                return ResourceManager.GetString("ObjectSelectionWizardPage_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce for .NET.
        /// </summary>
        internal static string ObjectSelectionWizardPage_Title {
            get {
                return ResourceManager.GetString("ObjectSelectionWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Salesforce connected app is named: {0} .
        /// </summary>
        internal static string RuntimeAuthentication_ConsumerKeyComment {
            get {
                return ResourceManager.GetString("RuntimeAuthentication_ConsumerKeyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose runtime authentication settings.
        /// </summary>
        internal static string RuntimeAuthenticationConfigWizardPage_Description {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationConfigWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Authentication Config.
        /// </summary>
        internal static string RuntimeAuthenticationConfigWizardPage_Legend {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationConfigWizardPage_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce for .NET.
        /// </summary>
        internal static string RuntimeAuthenticationConfigWizardPage_Title {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationConfigWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a runtime authentication model.
        /// </summary>
        internal static string RuntimeAuthenticationTypeWizardPage_Description {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationTypeWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Authentication.
        /// </summary>
        internal static string RuntimeAuthenticationTypeWizardPage_Legend {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationTypeWizardPage_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Salesforce for .NET.
        /// </summary>
        internal static string RuntimeAuthenticationTypeWizardPage_Title {
            get {
                return ResourceManager.GetString("RuntimeAuthenticationTypeWizardPage_Title", resourceCulture);
            }
        }
    }
}
