//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesforce.VisualStudio.Services.ConnectedService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SupportedProjectTypeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupportedProjectTypeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salesforce.VisualStudio.Services.ConnectedService.SupportedProjectTypeStrings", typeof(SupportedProjectTypeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# ASP.NET 4 Web Application.
        /// </summary>
        internal static string AspNet4Web {
            get {
                return ResourceManager.GetString("AspNet4Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Class Library.
        /// </summary>
        internal static string ClassLibrary {
            get {
                return ResourceManager.GetString("ClassLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Console Application.
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Windows Forms Application.
        /// </summary>
        internal static string WindowsForms {
            get {
                return ResourceManager.GetString("WindowsForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Windows Service.
        /// </summary>
        internal static string WindowsService {
            get {
                return ResourceManager.GetString("WindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# WPF Application.
        /// </summary>
        internal static string Wpf {
            get {
                return ResourceManager.GetString("Wpf", resourceCulture);
            }
        }
    }
}
