// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Salesforce.VisualStudio.Services.ConnectedService.Templates.CSharp
{
    using Salesforce.VisualStudio.Services.ConnectedService;
    using Salesforce.VisualStudio.Services.ConnectedService.CodeModel;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class SalesforceService : SalesforceServiceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Salesforce.Common;\r\nusing Salesforce.Force;\r\nusing System;\r\nusing System.Co" +
                    "llections.Generic;\r\nusing System.Configuration;\r\nusing System.Globalization;\r\nus" +
                    "ing System.Linq;\r\nusing System.Text;\r\nusing System.Threading.Tasks;\r\n");
            
            #line 16 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    if (generatedService.AuthenticationStrategy == AuthenticationStrategy.WebServerFlow)
    {

            
            #line default
            #line hidden
            this.Write("using System.Web;\r\n");
            
            #line 21 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 25 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generatedService.ServiceNamespace));
            
            #line default
            #line hidden
            this.Write(@"
{
    public class SalesforceService
    {
        public SalesforceService()
        {
            this.AuthenticationClient = new AuthenticationClient();
        }

        public AuthenticationClient AuthenticationClient { get; private set; }

");
            
            #line 36 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    if (generatedService.AuthenticationStrategy == AuthenticationStrategy.WebServerFlow)
    {

            
            #line default
            #line hidden
            this.Write(@"        public ForceClient GetWebServerForceClient()
        {
            if (!SalesforceService.IsAuthenticated())
            {
                throw new InvalidOperationException(""The user must be logged in to get a ForceClient."");
            }

            // Retrieve the access token and instance URL from the session object, which were set in the SalesforceOAuthRedirectHandler.
            this.AuthenticationClient.AccessToken = HttpContext.Current.Session[""AccessToken""] as string;
            this.AuthenticationClient.InstanceUrl = HttpContext.Current.Session[""InstanceUrl""] as string;
");
            
            #line 50 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write(@"        public async Task<ForceClient> GetUserNamePasswordForceClientAsync()
        {
#error Update the config file with the connected app's UserName, Password and SecurityToken. For more information, see the Next Steps section of the Getting Started documentation.

            await this.AuthenticationClient.UsernamePasswordAsync(
                SalesforceService.GetAppSetting(""");
            
            #line 60 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generatedService.ConfigurationKeyNames.ConsumerKey));
            
            #line default
            #line hidden
            this.Write("\"),\r\n                SalesforceService.GetAppSetting(\"");
            
            #line 61 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generatedService.ConfigurationKeyNames.ConsumerSecret));
            
            #line default
            #line hidden
            this.Write("\"),\r\n                SalesforceService.GetAppSetting(\"");
            
            #line 62 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generatedService.ConfigurationKeyNames.UserName));
            
            #line default
            #line hidden
            this.Write("\"),\r\n                SalesforceService.GetAppSetting(\"");
            
            #line 63 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generatedService.ConfigurationKeyNames.Password));
            
            #line default
            #line hidden
            this.Write("\") + SalesforceService.GetAppSetting(\"");
            
            #line 63 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generatedService.ConfigurationKeyNames.SecurityToken));
            
            #line default
            #line hidden
            this.Write("\", true),\r\n                SalesforceService.GetAppSetting(\"");
            
            #line 64 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(generatedService.ConfigurationKeyNames.Domain));
            
            #line default
            #line hidden
            this.Write("\") + \"/services/oauth2/token\");\r\n");
            
            #line 65 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    }

            
            #line default
            #line hidden
            this.Write(@"
            return new ForceClient(
                this.AuthenticationClient.InstanceUrl,
                this.AuthenticationClient.AccessToken,
                this.AuthenticationClient.ApiVersion);
        }

        /// <summary>
        /// Checks if the user is currently authenticated with a Salesforce AccessToken.
        /// </summary>
        public static bool IsAuthenticated()
        {
");
            
            #line 80 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    if (generatedService.AuthenticationStrategy == AuthenticationStrategy.WebServerFlow)
    {

            
            #line default
            #line hidden
            this.Write("            return HttpContext.Current.Session[\"AccessToken\"] != null;\r\n");
            
            #line 85 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("            throw new InvalidOperationException(\"IsAuthenticated not implemented " +
                    "for Authentication flows beyond Web Server Flow at this time\");\r\n");
            
            #line 91 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

    }

            
            #line default
            #line hidden
            this.Write(@"        }

        internal static string GetAppSetting(string name, bool isOptional = false)
        {
            string setting = ConfigurationManager.AppSettings[name];
            if (!isOptional && (String.IsNullOrWhiteSpace(setting) || string.Equals(setting, ""RequiredValue"", StringComparison.OrdinalIgnoreCase)))
            {
                throw new InvalidOperationException(
                    String.Format(CultureInfo.InvariantCulture, ""The value for the '{0}' key is missing from the appSettings section of the config file."", name));
            }
            else if (isOptional && (String.IsNullOrWhiteSpace(setting) || string.Equals(setting, ""OptionalValue"", StringComparison.OrdinalIgnoreCase)))
            {
                setting = null;
            }

            return setting;
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Repos\visual-studio-tools4\src\Salesforce.VisualStudio.Services\ConnectedService\Templates\CSharp\SalesforceService.tt"

private global::Salesforce.VisualStudio.Services.ConnectedService.CodeModel.GeneratedService _generatedServiceField;

/// <summary>
/// Access the generatedService parameter of the template.
/// </summary>
private global::Salesforce.VisualStudio.Services.ConnectedService.CodeModel.GeneratedService generatedService
{
    get
    {
        return this._generatedServiceField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool generatedServiceValueAcquired = false;
if (this.Session.ContainsKey("generatedService"))
{
    this._generatedServiceField = ((global::Salesforce.VisualStudio.Services.ConnectedService.CodeModel.GeneratedService)(this.Session["generatedService"]));
    generatedServiceValueAcquired = true;
}
if ((generatedServiceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("generatedService");
    if ((data != null))
    {
        this._generatedServiceField = ((global::Salesforce.VisualStudio.Services.ConnectedService.CodeModel.GeneratedService)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class SalesforceServiceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
